---
- hosts: test
  become: true

  tasks:
  - name: Create user1
    user:
      name: user1
      createhome: yes

  - name: Set authorized key.
    authorized_key:
      user: user1
      state: present
      key: "ssh-rsa" 
